version: '3.1'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  
  bbdd:
    build: 
      context: BBDD
      dockerfile: Dockerfile     
    ports:
      - "8010:4000"

  aplicacion:
    build: 
      context: Aplicacion
      dockerfile: Dockerfile     
    ports:
      - "8020:5000"

  tiempo:
    build: 
      context: Tiempo
      dockerfile: Dockerfile     
    ports:
      - "8030:3000"

volumes:
  mongodb_data_container: