version: '3.1'

services:

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql  
  
  aplicacion:
    build: 
      context: Aplicacion
      dockerfile: Dockerfile     
    ports:
      - "8020:4000"

  tiempo:
    build: 
      context: Tiempo
      dockerfile: Dockerfile     
    ports:
      - "8030:3000"
  

volumes:
  mysql_data: