version: '3.1'

services:
  aplicacion:
    build: 
      context: Aplicacion
      dockerfile: Dockerfile     
    ports:
      - "8020:4000"

  tiempo:
    build: 
      context: Tiempo
      dockerfile: Dockerfile     
    ports:
      - "8030:3000"