version: '3.1'

services:

  usuarios:
    build: 
      context: Usuarios
      dockerfile: Dockerfile     
    ports:
      - "8000:1000"

  ciudades:
    build: 
      context: Ciudades
      dockerfile: Dockerfile     
    ports:
      - "8010:4000"
  
  aplicacion:
    build: 
      context: Aplicacion
      dockerfile: Dockerfile     
    ports:
      - "8020:3000"
  

volumes:
  mongodb_data_container: